package model;
// Generated 7 Sep, 2017 7:26:20 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Batchschedule generated by hbm2java
 */
public class Batchschedule  implements java.io.Serializable {


     private Integer sid;
     private Batch batch;
     private Date sdate;
     private Date stime;
     private Date etime;
     private String status;
     private String remark;

    public Batchschedule() {
    }

    public Batchschedule(Batch batch, Date sdate, Date stime, Date etime, String status, String remark) {
       this.batch = batch;
       this.sdate = sdate;
       this.stime = stime;
       this.etime = etime;
       this.status = status;
       this.remark = remark;
    }
   
    public Integer getSid() {
        return this.sid;
    }
    
    public void setSid(Integer sid) {
        this.sid = sid;
    }
    public Batch getBatch() {
        return this.batch;
    }
    
    public void setBatch(Batch batch) {
        this.batch = batch;
    }
    public Date getSdate() {
        return this.sdate;
    }
    
    public void setSdate(Date sdate) {
        this.sdate = sdate;
    }
    public Date getStime() {
        return this.stime;
    }
    
    public void setStime(Date stime) {
        this.stime = stime;
    }
    public Date getEtime() {
        return this.etime;
    }
    
    public void setEtime(Date etime) {
        this.etime = etime;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

    @Override
    public String toString() {
        return "Batchschedule{" + "sid=" + sid + ", batch=" + batch + ", sdate=" + sdate + ", stime=" + stime + ", etime=" + etime + ", status=" + status + ", remark=" + remark + '}';
    }




}


