package java.model;
// Generated 7 Sep, 2017 7:26:20 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Batch generated by hbm2java
 */
public class Batch  implements java.io.Serializable {


     private String batchcode;
     private Consultant consultant;
     private Courses courses;
     private Department department;
     private Division division;
     private Employees employeesByLocalSpoc;
     private Employees employeesBySoftSkillTrainer;
     private Employees employeesByTechTrainer;
     private University university;
     private String fbgroup;
     private Date startingDate;
     private String track;
     private String status;
     private String uniSpocName;
     private String uniSpocContact;
     private String schedule;
     private Set batchschedules = new HashSet(0);

    public Batch() {
    }

	
    public Batch(String batchcode) {
        this.batchcode = batchcode;
    }
    public Batch(String batchcode, Consultant consultant, Courses courses, Department department, Division division, Employees employeesByLocalSpoc, Employees employeesBySoftSkillTrainer, Employees employeesByTechTrainer, University university, String fbgroup, Date startingDate, String track, String status, String uniSpocName, String uniSpocContact, String schedule, Set batchschedules) {
       this.batchcode = batchcode;
       this.consultant = consultant;
       this.courses = courses;
       this.department = department;
       this.division = division;
       this.employeesByLocalSpoc = employeesByLocalSpoc;
       this.employeesBySoftSkillTrainer = employeesBySoftSkillTrainer;
       this.employeesByTechTrainer = employeesByTechTrainer;
       this.university = university;
       this.fbgroup = fbgroup;
       this.startingDate = startingDate;
       this.track = track;
       this.status = status;
       this.uniSpocName = uniSpocName;
       this.uniSpocContact = uniSpocContact;
       this.schedule = schedule;
       this.batchschedules = batchschedules;
    }
   
    public String getBatchcode() {
        return this.batchcode;
    }
    
    public void setBatchcode(String batchcode) {
        this.batchcode = batchcode;
    }
    public Consultant getConsultant() {
        return this.consultant;
    }
    
    public void setConsultant(Consultant consultant) {
        this.consultant = consultant;
    }
    public Courses getCourses() {
        return this.courses;
    }
    
    public void setCourses(Courses courses) {
        this.courses = courses;
    }
    public Department getDepartment() {
        return this.department;
    }
    
    public void setDepartment(Department department) {
        this.department = department;
    }
    public Division getDivision() {
        return this.division;
    }
    
    public void setDivision(Division division) {
        this.division = division;
    }
    public Employees getEmployeesByLocalSpoc() {
        return this.employeesByLocalSpoc;
    }
    
    public void setEmployeesByLocalSpoc(Employees employeesByLocalSpoc) {
        this.employeesByLocalSpoc = employeesByLocalSpoc;
    }
    public Employees getEmployeesBySoftSkillTrainer() {
        return this.employeesBySoftSkillTrainer;
    }
    
    public void setEmployeesBySoftSkillTrainer(Employees employeesBySoftSkillTrainer) {
        this.employeesBySoftSkillTrainer = employeesBySoftSkillTrainer;
    }
    public Employees getEmployeesByTechTrainer() {
        return this.employeesByTechTrainer;
    }
    
    public void setEmployeesByTechTrainer(Employees employeesByTechTrainer) {
        this.employeesByTechTrainer = employeesByTechTrainer;
    }
    public University getUniversity() {
        return this.university;
    }
    
    public void setUniversity(University university) {
        this.university = university;
    }
    public String getFbgroup() {
        return this.fbgroup;
    }
    
    public void setFbgroup(String fbgroup) {
        this.fbgroup = fbgroup;
    }
    public Date getStartingDate() {
        return this.startingDate;
    }
    
    public void setStartingDate(Date startingDate) {
        this.startingDate = startingDate;
    }
    public String getTrack() {
        return this.track;
    }
    
    public void setTrack(String track) {
        this.track = track;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getUniSpocName() {
        return this.uniSpocName;
    }
    
    public void setUniSpocName(String uniSpocName) {
        this.uniSpocName = uniSpocName;
    }
    public String getUniSpocContact() {
        return this.uniSpocContact;
    }
    
    public void setUniSpocContact(String uniSpocContact) {
        this.uniSpocContact = uniSpocContact;
    }
    public String getSchedule() {
        return this.schedule;
    }
    
    public void setSchedule(String schedule) {
        this.schedule = schedule;
    }
    public Set getBatchschedules() {
        return this.batchschedules;
    }
    
    public void setBatchschedules(Set batchschedules) {
        this.batchschedules = batchschedules;
    }

}


