package model;
// Generated 7 Sep, 2017 7:26:20 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Consultant generated by hbm2java
 */
public class Consultant  implements java.io.Serializable {


     private Integer consultantId;
     private Division division;
     private Employees employees;
     private String type;
     private Set batches = new HashSet(0);

    public Consultant() {
    }

	
    public Consultant(Division division, Employees employees) {
        this.division = division;
        this.employees = employees;
    }
    public Consultant(Division division, Employees employees, String type, Set batches) {
       this.division = division;
       this.employees = employees;
       this.type = type;
       this.batches = batches;
    }
   
    public Integer getConsultantId() {
        return this.consultantId;
    }
    
    public void setConsultantId(Integer consultantId) {
        this.consultantId = consultantId;
    }
    public Division getDivision() {
        return this.division;
    }
    
    public void setDivision(Division division) {
        this.division = division;
    }
    public Employees getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Employees employees) {
        this.employees = employees;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Set getBatches() {
        return this.batches;
    }
    
    public void setBatches(Set batches) {
        this.batches = batches;
    }




}


