package model;
// Generated 7 Sep, 2017 7:26:20 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Courses generated by hbm2java
 */
public class Courses  implements java.io.Serializable {


     private Integer cid;
     private String track;
     private String cname;
     private Integer chours;
     private String discription;
     private Set employeeses = new HashSet(0);
     private Set trainers = new HashSet(0);
     private Set batches = new HashSet(0);

    public Courses() {
    }

    public Courses(String track, String cname, Integer chours, String discription, Set employeeses, Set trainers, Set batches) {
       this.track = track;
       this.cname = cname;
       this.chours = chours;
       this.discription = discription;
       this.employeeses = employeeses;
       this.trainers = trainers;
       this.batches = batches;
    }
   
    public Integer getCid() {
        return this.cid;
    }
    
    public void setCid(Integer cid) {
        this.cid = cid;
    }
    public String getTrack() {
        return this.track;
    }
    
    public void setTrack(String track) {
        this.track = track;
    }
    public String getCname() {
        return this.cname;
    }
    
    public void setCname(String cname) {
        this.cname = cname;
    }
    public Integer getChours() {
        return this.chours;
    }
    
    public void setChours(Integer chours) {
        this.chours = chours;
    }
    public String getDiscription() {
        return this.discription;
    }
    
    public void setDiscription(String discription) {
        this.discription = discription;
    }
    public Set getEmployeeses() {
        return this.employeeses;
    }
    
    public void setEmployeeses(Set employeeses) {
        this.employeeses = employeeses;
    }
    public Set getTrainers() {
        return this.trainers;
    }
    
    public void setTrainers(Set trainers) {
        this.trainers = trainers;
    }
    public Set getBatches() {
        return this.batches;
    }
    
    public void setBatches(Set batches) {
        this.batches = batches;
    }




}


