package model;
// Generated 7 Sep, 2017 7:26:20 PM by Hibernate Tools 4.3.1



/**
 * District generated by hbm2java
 */
public class District  implements java.io.Serializable {


     private Integer did;
     private Division division;
     private String dname;

    public District() {
    }

    public District(Division division, String dname) {
       this.division = division;
       this.dname = dname;
    }
   
    public Integer getDid() {
        return this.did;
    }
    
    public void setDid(Integer did) {
        this.did = did;
    }
    public Division getDivision() {
        return this.division;
    }
    
    public void setDivision(Division division) {
        this.division = division;
    }
    public String getDname() {
        return this.dname;
    }
    
    public void setDname(String dname) {
        this.dname = dname;
    }




}


