package model;
// Generated 7 Sep, 2017 7:26:20 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Division generated by hbm2java
 */
public class Division  implements java.io.Serializable {


     private Integer divisionId;
     private String dname;
     private Set consultants = new HashSet(0);
     private Set batches = new HashSet(0);
     private Set districts = new HashSet(0);
     private Set universities = new HashSet(0);
     private Set employeeses = new HashSet(0);

    public Division() {
    }

	
    public Division(String dname) {
        this.dname = dname;
    }
    public Division(String dname, Set consultants, Set batches, Set districts, Set universities, Set employeeses) {
       this.dname = dname;
       this.consultants = consultants;
       this.batches = batches;
       this.districts = districts;
       this.universities = universities;
       this.employeeses = employeeses;
    }
   
    public Integer getDivisionId() {
        return this.divisionId;
    }
    
    public void setDivisionId(Integer divisionId) {
        this.divisionId = divisionId;
    }
    public String getDname() {
        return this.dname;
    }
    
    public void setDname(String dname) {
        this.dname = dname;
    }
    public Set getConsultants() {
        return this.consultants;
    }
    
    public void setConsultants(Set consultants) {
        this.consultants = consultants;
    }
    public Set getBatches() {
        return this.batches;
    }
    
    public void setBatches(Set batches) {
        this.batches = batches;
    }
    public Set getDistricts() {
        return this.districts;
    }
    
    public void setDistricts(Set districts) {
        this.districts = districts;
    }
    public Set getUniversities() {
        return this.universities;
    }
    
    public void setUniversities(Set universities) {
        this.universities = universities;
    }
    public Set getEmployeeses() {
        return this.employeeses;
    }
    
    public void setEmployeeses(Set employeeses) {
        this.employeeses = employeeses;
    }




}


