package model;
// Generated 7 Sep, 2017 7:26:20 PM by Hibernate Tools 4.3.1



/**
 * EmpStatus generated by hbm2java
 */
public class EmpStatus  implements java.io.Serializable {


     private int statusId;
     private String status;

    public EmpStatus() {
    }

	
    public EmpStatus(int statusId) {
        this.statusId = statusId;
    }
    public EmpStatus(int statusId, String status) {
       this.statusId = statusId;
       this.status = status;
    }
   
    public int getStatusId() {
        return this.statusId;
    }
    
    public void setStatusId(int statusId) {
        this.statusId = statusId;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


