package model;
// Generated 7 Sep, 2017 7:26:20 PM by Hibernate Tools 4.3.1



/**
 * LictUgrightsId generated by hbm2java
 */
public class LictUgrightsId  implements java.io.Serializable {


     private String tableName;
     private int groupId;

    public LictUgrightsId() {
    }

    public LictUgrightsId(String tableName, int groupId) {
       this.tableName = tableName;
       this.groupId = groupId;
    }
   
    public String getTableName() {
        return this.tableName;
    }
    
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }
    public int getGroupId() {
        return this.groupId;
    }
    
    public void setGroupId(int groupId) {
        this.groupId = groupId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LictUgrightsId) ) return false;
		 LictUgrightsId castOther = ( LictUgrightsId ) other; 
         
		 return ( (this.getTableName()==castOther.getTableName()) || ( this.getTableName()!=null && castOther.getTableName()!=null && this.getTableName().equals(castOther.getTableName()) ) )
 && (this.getGroupId()==castOther.getGroupId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getTableName() == null ? 0 : this.getTableName().hashCode() );
         result = 37 * result + this.getGroupId();
         return result;
   }   


}


