package model;
// Generated 7 Sep, 2017 7:26:20 PM by Hibernate Tools 4.3.1



/**
 * LictUgmembers generated by hbm2java
 */
public class LictUgmembers  implements java.io.Serializable {


     private LictUgmembersId id;

    public LictUgmembers() {
    }

    public LictUgmembers(LictUgmembersId id) {
       this.id = id;
    }
   
    public LictUgmembersId getId() {
        return this.id;
    }
    
    public void setId(LictUgmembersId id) {
        this.id = id;
    }




}


