package model;
// Generated 7 Sep, 2017 7:26:20 PM by Hibernate Tools 4.3.1



/**
 * LictUgrights generated by hbm2java
 */
public class LictUgrights  implements java.io.Serializable {


     private LictUgrightsId id;
     private String accessMask;

    public LictUgrights() {
    }

	
    public LictUgrights(LictUgrightsId id) {
        this.id = id;
    }
    public LictUgrights(LictUgrightsId id, String accessMask) {
       this.id = id;
       this.accessMask = accessMask;
    }
   
    public LictUgrightsId getId() {
        return this.id;
    }
    
    public void setId(LictUgrightsId id) {
        this.id = id;
    }
    public String getAccessMask() {
        return this.accessMask;
    }
    
    public void setAccessMask(String accessMask) {
        this.accessMask = accessMask;
    }




}


