package model;
// Generated 7 Sep, 2017 7:26:20 PM by Hibernate Tools 4.3.1



/**
 * LictUgmembersId generated by hbm2java
 */
public class LictUgmembersId  implements java.io.Serializable {


     private String userName;
     private int groupId;

    public LictUgmembersId() {
    }

    public LictUgmembersId(String userName, int groupId) {
       this.userName = userName;
       this.groupId = groupId;
    }
   
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public int getGroupId() {
        return this.groupId;
    }
    
    public void setGroupId(int groupId) {
        this.groupId = groupId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LictUgmembersId) ) return false;
		 LictUgmembersId castOther = ( LictUgmembersId ) other; 
         
		 return ( (this.getUserName()==castOther.getUserName()) || ( this.getUserName()!=null && castOther.getUserName()!=null && this.getUserName().equals(castOther.getUserName()) ) )
 && (this.getGroupId()==castOther.getGroupId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUserName() == null ? 0 : this.getUserName().hashCode() );
         result = 37 * result + this.getGroupId();
         return result;
   }   


}


