package model;
// Generated 7 Sep, 2017 7:26:20 PM by Hibernate Tools 4.3.1



/**
 * LictUggroups generated by hbm2java
 */
public class LictUggroups  implements java.io.Serializable {


     private Integer groupId;
     private String label;

    public LictUggroups() {
    }

    public LictUggroups(String label) {
       this.label = label;
    }
   
    public Integer getGroupId() {
        return this.groupId;
    }
    
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }
    public String getLabel() {
        return this.label;
    }
    
    public void setLabel(String label) {
        this.label = label;
    }




}


