package model;
// Generated 7 Sep, 2017 7:26:20 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Project1Audit generated by hbm2java
 */
public class Project1Audit  implements java.io.Serializable {


     private Integer id;
     private Date datetime;
     private String ip;
     private String user;
     private String table;
     private String action;
     private String description;

    public Project1Audit() {
    }

	
    public Project1Audit(Date datetime, String ip, String action) {
        this.datetime = datetime;
        this.ip = ip;
        this.action = action;
    }
    public Project1Audit(Date datetime, String ip, String user, String table, String action, String description) {
       this.datetime = datetime;
       this.ip = ip;
       this.user = user;
       this.table = table;
       this.action = action;
       this.description = description;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Date getDatetime() {
        return this.datetime;
    }
    
    public void setDatetime(Date datetime) {
        this.datetime = datetime;
    }
    public String getIp() {
        return this.ip;
    }
    
    public void setIp(String ip) {
        this.ip = ip;
    }
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }
    public String getTable() {
        return this.table;
    }
    
    public void setTable(String table) {
        this.table = table;
    }
    public String getAction() {
        return this.action;
    }
    
    public void setAction(String action) {
        this.action = action;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


