package model;
// Generated 7 Sep, 2017 7:26:20 PM by Hibernate Tools 4.3.1



/**
 * Roles generated by hbm2java
 */
public class Roles  implements java.io.Serializable {


     private Integer roleid;
     private String rolename;
     private String remark;

    public Roles() {
    }

    public Roles(String rolename, String remark) {
       this.rolename = rolename;
       this.remark = remark;
    }
   
    public Integer getRoleid() {
        return this.roleid;
    }
    
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }
    public String getRolename() {
        return this.rolename;
    }
    
    public void setRolename(String rolename) {
        this.rolename = rolename;
    }
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }




}


