package model;
// Generated 7 Sep, 2017 7:26:20 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Trainer generated by hbm2java
 */
public class Trainer  implements java.io.Serializable {


     private Long id;
     private Courses courses;
     private Date date;
     private String emailid;
     private String experience;
     private String mobile;
     private String name;
     private String natianality;
     private String password;
     private String qualification;
     private Date registeredDate;
     private String skillset;
     private String skype;
     private String username;
     private String usertype;
     private String whatsapp;
     private String photo;

    public Trainer() {
    }

    public Trainer(Courses courses, Date date, String emailid, String experience, String mobile, String name, String natianality, String password, String qualification, Date registeredDate, String skillset, String skype, String username, String usertype, String whatsapp, String photo) {
       this.courses = courses;
       this.date = date;
       this.emailid = emailid;
       this.experience = experience;
       this.mobile = mobile;
       this.name = name;
       this.natianality = natianality;
       this.password = password;
       this.qualification = qualification;
       this.registeredDate = registeredDate;
       this.skillset = skillset;
       this.skype = skype;
       this.username = username;
       this.usertype = usertype;
       this.whatsapp = whatsapp;
       this.photo = photo;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Courses getCourses() {
        return this.courses;
    }
    
    public void setCourses(Courses courses) {
        this.courses = courses;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getEmailid() {
        return this.emailid;
    }
    
    public void setEmailid(String emailid) {
        this.emailid = emailid;
    }
    public String getExperience() {
        return this.experience;
    }
    
    public void setExperience(String experience) {
        this.experience = experience;
    }
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getNatianality() {
        return this.natianality;
    }
    
    public void setNatianality(String natianality) {
        this.natianality = natianality;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getQualification() {
        return this.qualification;
    }
    
    public void setQualification(String qualification) {
        this.qualification = qualification;
    }
    public Date getRegisteredDate() {
        return this.registeredDate;
    }
    
    public void setRegisteredDate(Date registeredDate) {
        this.registeredDate = registeredDate;
    }
    public String getSkillset() {
        return this.skillset;
    }
    
    public void setSkillset(String skillset) {
        this.skillset = skillset;
    }
    public String getSkype() {
        return this.skype;
    }
    
    public void setSkype(String skype) {
        this.skype = skype;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getUsertype() {
        return this.usertype;
    }
    
    public void setUsertype(String usertype) {
        this.usertype = usertype;
    }
    public String getWhatsapp() {
        return this.whatsapp;
    }
    
    public void setWhatsapp(String whatsapp) {
        this.whatsapp = whatsapp;
    }
    public String getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(String photo) {
        this.photo = photo;
    }




}


